name: Deploy Cloud Run Job

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west1
  REPOSITORY: ar-repo-vidscribe
  IMAGE: job-vidscribe

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/673831532349/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider-instance'
          service_account: 'github-actions-deployer@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Docker Auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          
      - name: Build and Push Container
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"
          docker build -t "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: Deploy to Cloud Run Jobs
        run: |-
          # Export the variable so envsubst can swap it in the YAML
          export IMAGE_URL="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"
          
          envsubst < deploy/cloudrun-job.yaml > cloudrun-job-deployed.yaml
          
          gcloud run jobs replace cloudrun-job-deployed.yaml \
            --region=${{ env.REGION }} \
            --project=${{ env.PROJECT_ID }}
